export { default as getDragon } from './getDragon'
export { default as DeleteDragon } from './deleteDragon'
export { default as GetDragonDetail } from './detailDragon'
export { default as AddDragons } from './addDragon'
export { default as UpdateDragons } from './updateDragon'
